name: Ubuntu 22.04 Swift Release CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:

  exec-ci-release-22_04:
    runs-on: ubuntu-22.04

    steps:
      - uses: swift-actions/setup-swift@v1
        with:
            swift-version: "5.8"

      - name: Checkout repo
        uses: actions/checkout@v2
      
      #- name: Reconfigure Private Repo URLs
      #  run: sed -i 's/git@github.com:/https:\/\/${{ secrets.ACCESS_TOKEN }}@github.com\//g' Package.swift

      - name: Release build
        run: swift build -c release

      - name: Release Test
        run: swift test -c release
